- name: Install Prometheus and Node Exporter (and NTP)
  package:
    name: 
      - prometheus
      - prometheus-node-exporter
      - ntp
    state: present

- name: Start and enable Prometheus and Node Exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - prometheus
    - prometheus-node-exporter

- name: Configure Prometheus
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0640

- name: Configure Prometheus rules
  template:
    src: rules.yml
    dest: /etc/prometheus/rules.yml
    owner: prometheus
    group: prometheus
    mode: 0640

- name: Configure NTP
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0640

- name: Restart Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes

- name: Restart Node Exporter
  service:
    name: prometheus-node-exporter
    state: restarted
    enabled: yes

- name: Restart NTP
  service:
    name: ntp
    state: restarted
    enabled: yes