- name: Install PHP 7.4 and PHP 7.4-FPM
  apt:
    name:
      - php7.4
      - php7.4-fpm
      - php-mysql
    state: present
    
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create .txt version files
  shell: touch /data/{{ item }}.txt
  loop:
    - prev_version
    - current_version

- name: Create current_version.txt
  shell: touch /data/current_version.txt

- name: Create Nginx configuration file
  template:
    src: back
    dest: /etc/nginx/sites-available/back
    owner: "{{ vault_ansible_user }}"
    group: "{{ vault_ansible_password }}"
    mode: 0644

- name: Create Nginx symbolic link
  command: ln -sfn /etc/nginx/sites-available/back /etc/nginx/sites-enabled/

- name: Delete default nginx.conf symbolic link
  command: rm -f /etc/nginx/sites-enabled/default

- name: Enable automatic restart of services
  command: systemctl enable {{ item }} 
  loop:
    - nginx
    - php7.4-fpm

- name: Restart services
  service:
    name: nginx
    state: restarted 
  loop:
    - nginx
    - php7.4-fpm