configs:

    use: 'server'

    server:
        name: "server1"
        public_ip: '192.168.153.117'        
        
    front:
      name: "server_front"
      public_ip: '192.168.153.118'

    back:
      name: "server_back"
      public_ip: '192.168.153.118'
    
    db:
      name: "server_db"
      public_ip: '192.168.153.118'
        