configs:
  front:
    name: "front"
    ip:  ""     

  back:
    name: "back"
    ip:  ""     
  
  db:
    name: "db"
    ip:  ""  
  
  vm1:
    name: "terminal"
    ip:  ""     
        
vars:
  box: "debian/bullseye64"