configs:
   front
      name: "example"
      ip:  "192.168.154.12"     

    back:
      name: ""
      ip:  ""     
    
    db:
      name: ""
      ip:  ""  
   
    vm1:
      name: ""
      ip:  ""     
        
vars:
  box: "debian/bullseye64"