configs:   

  back:
    name: "back"
    ip: ""
    memory: 1024
    cpus: 2
 
    
  front:
    name: "front"
    ip: ""
    memory: 1024
    cpus: 2

  db:
    name: "db"
    ip: ""
    memory: 1024
    cpus: 2

  terminal:
    name: "terminal"
    ip: "" 
    memory: 8192 
    cpus: 2

vars:
  box: "debian/bullseye64"  
  runner_register_token: ""