- name: Download front Artifact
  get_url:
    url: http://{{ nexus_server_address }}:{{ nexus_server_port }}/repository/maven-releases/frontend/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ version }}.tar
    dest: /var/www/html/{{ artifact_id }}-{{ version }}.tar

- name: Extract .tar archive
  unarchive:
    src: /var/www/html/{{ artifact_id }}-{{ version }}.tar
    dest: /var/www/html/
    remote_src: yes
  
- name: Remove front folder (if it exists)
  command: rm -rf /var/www/html/front

- name: Rename front folder
  command: mv /var/www/html/artifacts /var/www/html/front 

- name: Remove front folder
  command: rm -rf /var/www/html/{{ artifact_id }}-{{ version }}.tar

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
