- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create artifacts folder
  command: mkdir -p /data/artifacts

- name: Create prev_version.txt
  shell: touch /data/prev_version.txt

- name: Create current_version.txt
  shell: touch /data/current_version.txt

- name: Create Nginx configuration file
  template:
    src: front
    dest: /etc/nginx/sites-available/front
    owner: "{{ ansible_user }}"
    group: "{{ ansible_password }}"
    mode: 0644

- name: Create Nginx symbolic link
  command: ln -sfn /etc/nginx/sites-available/front /etc/nginx/sites-enabled/

- name: Delete default nginx.conf symbolic link
  command: rm -f /etc/nginx/sites-enabled/default

- name: Enable automatic restart of Nginx service
  command: systemctl enable nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted