- name: Register hosts to know_hosts
  hosts: front_servers
  gather_facts: false
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: common
        tasks_from: register_hosts.yml

- name: Deploy front
  hosts: front_servers
  vars:
    artifact_id: "{{ artifact_id }}"
    version: "{{ version }}"
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: front
        tasks_from: deploy_stack.yml