- name: Deploy front
  hosts: front_servers
  become: true
  vars:
    artifact_id: "{{ front_artifact_id }}"
    version: "{{ front_version }}"
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: front
        tasks_from: deploy_stack.yml

- name: Backup database
  hosts: database_servers
  become: true
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: database
        tasks_from: backup.yml

- name: Deploy back
  hosts: back_servers
  become: true
  vars:
    artifact_id: "{{ back_artifact_id }}"
    version: "{{ back_version }}"
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: back
        tasks_from: deploy_stack.yml