- name: Register hosts to know_hosts
  hosts: all
  gather_facts: false
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: common
        tasks_from: register_hosts.yml

- name: Reboot all servers
  hosts: all
  become: true
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - include_role:
        name: common
        tasks_from: reboot.yml