- name: Revert front
  hosts: front_servers
  become: true
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - name: Read prev_version.txt
      shell: cat /data/prev_version.txt
      register: prev_version

    - include_role:
        name: front
        tasks_from: revert.yml
      when: prev_version != ""